### ISSUE TITLE
As a user, I can fill in my habits in the info page, so I can match with different people who have similar habits with me

### ISSUE THREAD

**Issue by HaifengXiao-29** [xlab-classes/cse442-spring2022-team-heart#35]

**Comment by Chuanlong21** [comment]
Acceptance test 1:

1. Users can go to web with (http://cheshire.cse.buffalo.edu:8080/web_war/SignIn.html)
2. Users click the register button to sign up 
3. Users should enter username, email, password, and confirm password to set up an account, then click next to go to the verification page
4. Users need to go to email to check the verification code to enter, then click done button
5. Users need to fill in the interest page in order to match people.
6. Then click done button to go to the match page.
7. Click match button to chat with people.
